"""create city, attraction, accommodation, search

Revision ID: da9415c179aa
Revises: ef6eb4f8891e
Create Date: 2025-07-23 17:59:13.595142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9415c179aa'
down_revision: Union[str, Sequence[str], None] = 'ef6eb4f8891e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
